name: Shinobi CI

on: [push, pull_request]

jobs:
  build:
    name: ${{ matrix.os }} - ${{ matrix.config.variation }}
    runs-on: ${{ matrix.os }}
    timeout-minutes: 10
    strategy:
      matrix:
        os: [ubuntu-latest]
        config:
          - {variation: 'standard', generate_options: ''}
        include:
          - os: ubuntu-latest
            config: {variation: 'ASAN', generate_options: '-DASAN=ON -DCMAKE_BUILD_TYPE=Debug -DCMAKE_CXX_FLAGS="-Wall -Werror"'}
#          - os: ubuntu-latest
#            config: {variation: 'debug-log', generate_options: '-DCMAKE_C_FLAGS="-Wall -Werror"'}
    steps:
      - uses: actions/checkout@v2
      - name: Environment Information
        run: npx envinfo
      - name: Install LLVM
        # TODO(cjihrig): Get rid of this. Maybe move LLVM in tree?
        uses: KyleMayes/install-llvm-action@v1
        with:
          version: "16"
      - name: Build and Test
        run: |
          cmake ${{ matrix.config.generate_options }} .
          cmake --build . --target check
